# k8s/deployment.yaml
apiVersion: apps/v1           # Deployment API versiyonu
kind: Deployment              # Bu kaynak bir Deployment olduğunu tanımlar
metadata:
  name: test-cicd             # Deployment adı
spec:
  replicas: 1                 # Kaç pod çalışacağı
  selector:
    matchLabels:
      app: test-cicd          # Pod etiketleri bu selector ile eşleşmeli
  template:
    metadata:
      labels:
        app: test-cicd        # Pod’a atanan etiket
    spec:
      containers:
      - name: app             # Container adı
        image: softsaw/test-cicd:latest  # Çekilecek Docker image’i
        ports:
        - containerPort: 5000 # Container içindeki port